name: 生成文件

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: 配置环境
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jre python2.7
    - name: 执行命令
      run: |
        echo 下载文件
        wget https://hugeota.d.miui.com/21.2.3/miui_GRUS_21.2.3_60342cd1f2_11.0.zip
        chmod +x start.sh
        bash start.sh
    - name: update to repo
      run: |
        git config --global user.name ${{ secrets.GITHUBUSER }}
        git config --global user.email ${{ secrets.GITHUBEMAIL }}
        git add eufix-magisk-model-ver.zip && echo 添加变动文件
        git commit -m 'update to repo' && echo commit
        git push origin master && echo push!
